server:
  port: 8080

logging:
  level:
    root: warn
    ru: info

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: filmorate
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect