SELECT * FROM FILMS;

INSERT INTO GENRE VALUES (1, 'Комедия');
INSERT INTO GENRE VALUES (2, 'Ужасы');
INSERT INTO GENRE VALUES (3, 'Боевик');

INSERT INTO MPA VALUES (1, '6+');
INSERT INTO MPA VALUES (2, '12+');
INSERT INTO MPA VALUES (3, '18+');