SELECT * FROM FILMS;

INSERT INTO GENRE VALUES (1, 'Комедия');
INSERT INTO GENRE VALUES (2, 'Ужасы');
INSERT INTO GENRE VALUES (3, 'Боевик');
INSERT INTO GENRE VALUES (4, 'Мелодрама');
INSERT INTO GENRE VALUES (5, 'Приключения');

INSERT INTO MPA VALUES (1, '6+');
INSERT INTO MPA VALUES (2, '10+');
INSERT INTO MPA VALUES (3, '14+');
INSERT INTO MPA VALUES (4, '16+');
INSERT INTO MPA VALUES (5, '18+');